language: perl
perl: 5.18-shrplib
#env: PERL_CPANM_OPT="--mirror http://cpan.mirrors.travis-ci.org  --mirror http://cpan.cpantesters.org/ --mirror http://search.cpan.org/CPAN --cascade-search --local-lib . --notest --force --skip-satisfied" PATH=./bin:$PATH PERL5LIB=$PERL5LIB:lib/perl5
env: PERL_CPANM_OPT="--verbose --notest --force --skip-satisfied" 
#addons:
#  homebrew:
#    taps: brewsci/bio
#    packages: jellyfish
before_install:
  - "cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)"
  - "echo $PERL5LIB"
  - "echo $PATH"
    #- "perl -MBio::Kmer -MData::Dumper -e 'print Dumper \%INC;'"

